import { applyUpdater } from './utils';

export const createUiSlice = (set) => ({
  activeLocation: null,
  locationData: null,
  uiMode: null,
  activePanel: null,
  appMode: 'explore',
  buildMode: false,
  impactData: null,
  demographics: null,
  locationPopulation: null,
  urbanAnalysis: null,
  analysisLoading: false,
  facilityCheckOpen: false,
  showLayersMenu: false,
  showSuggestions: false,
  facilityViewMode: 'coverage',
  hoveredFacility: null,
  floodMode: false,
  debugMode: false,
  notification: null,

  setActiveLocation: (loc) => set({ activeLocation: loc }),
  setActivePanel: (panel) => set((state) => ({ activePanel: state.activePanel === panel ? null : panel })),
  setAppMode: (mode) => set({ appMode: mode }),
  setBuildMode: (active) => set((state) => ({ buildMode: typeof active === 'function' ? active(state.buildMode) : active })),
  setLocationData: (data) => set((state) => ({ locationData: applyUpdater(data, state.locationData) })),
  setUiMode: (mode) => set({ uiMode: mode }),
  setImpactData: (data) => set({ impactData: data }),
  setDemographics: (data) => set({ demographics: data }),
  setLocationPopulation: (pop) => set({ locationPopulation: pop }),
  setUrbanAnalysis: (analysis) => set({ urbanAnalysis: analysis }),
  setAnalysisLoading: (loading) => set({ analysisLoading: loading }),
  setFacilityCheckOpen: (open) => set((state) => ({ facilityCheckOpen: applyUpdater(open, state.facilityCheckOpen) })),
  setShowLayersMenu: (show) => set((state) => ({ showLayersMenu: applyUpdater(show, state.showLayersMenu) })),
  setShowSuggestions: (show) => set({ showSuggestions: show }),
  setFacilityViewMode: (mode) => set({ facilityViewMode: mode }),
  setHoveredFacility: (facility) => set({ hoveredFacility: facility }),
  setFloodMode: (mode) => set((state) => ({ floodMode: typeof mode === 'function' ? mode(state.floodMode) : mode })),
  setDebugMode: (mode) => set({ debugMode: mode }),
  setNotification: (msg) => set({ notification: msg }),
  clearNotification: () => set({ notification: null }),
});
